function [ioPlotHistValues] = graphHistogramModule(iLeaves, ...
                                             ioPlotHistValues, ...
                                             iBinsValue)
%% GRAPHHISTOGRAMMODULE 
% Summary of this function goes here. 
% 
% * Syntax 
% 
%	[IOPLOTHISTVALUES] = GRAPHHISTOGRAMMODULE(ILEAVES,
%                                              IOPLOTHISTVALUES;
%                                              IBINSVALUE)
% 
% * Input 
% 
% -- iLeaves - 
% 
% -- ioPlotHistValues -  
% 
% -- iBinsValue -  
% 
% * Output 
% 
% -- ioPlotHistValues -  
% 
% * Examples: 
% 
% Provide sample usage code here
% 
% * See also: 
% 
% List related files here 
% 
% * Author: Dmitrii Leliuhin 
% * Email: dleliuhin@mail.ru 
% * Date: 12/10/2018 01:41:59 
% * Version: 1.0 $ 
% * Requirements: PCWIN64, MatLab R2016a 
% 
% * Warning: 
% 
% # Warnings list. 
% 
% * TODO: 
% 
% # TODO list. 
% 

%% Code 

%-----------------Stats_R histogram-----------------------------------
figure;
set(gcf, 'Position', [300, 100, 800, 600]);
subplot(2,2,1);
[ioPlotHistValues.nh1.R.Contrast, ...
 ioPlotHistValues.h.R.Contrast] = plotHist(nh1.R.Contrast, ...
                                          h.R.Contrast, ...
                                          ' stats R.Contrast', ...
                                          iBinsValue);

subplot(2,2,2);
[ioPlotHistValues.nh1.R.Correlation, ...
 ioPlotHistValues.h.R.Correlation] = plotHist(nh1.R.Correlation, ...
                                          h.R.Correlation, ...
                                          ' stats R.Contrast', ...
                                          iBinsValue);
subplot(2,2,3);
[ioPlotHistValues.nh1.R.Energy, ...
 ioPlotHistValues.h.R.Energy] = plotHist(nh1.R.Energy, ...
                                          h.R.Energy, ...
                                          ' stats R.Contrast', ...
                                          iBinsValue);

subplot(2,2,4);
[ioPlotHistValues.nh1.R.Homogeneity, ...
 ioPlotHistValues.h.R.Homogeneity] = plotHist(nh1.R.Homogeneity, ...
                                          h.R.Homogeneity, ...
                                          ' stats R.Contrast', ...
                                          iBinsValue);

set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
saveas(gcf,'Result/graphHistorgamResults/R.jpg');
saveas(gcf,'Result/graphHistorgamResults/R.fig');

%-----------------Stats_G histogram------------------------------
figure;
set(gcf, 'Position', [300, 100, 800, 600]);
subplot(2,2,1);
[ioPlotHistValues.nh1.G.Contrast, ...
 ioPlotHistValues.h.G.Contrast] = plotHist(nh1.G.Contrast, ...
                                          h.G.Contrast, ...
                                          ' stats G.Contrast', ...
                                          iBinsValue);

subplot(2,2,2);
[ioPlotHistValues.nh1.G.Correlation, ...
 ioPlotHistValues.h.G.Correlation] = plotHist(nh1.G.Correlation, ...
                                          h.G.Correlation, ...
                                          ' stats G.Correlation', ...
                                          iBinsValue);
subplot(2,2,3);
[ioPlotHistValues.nh1.G.Energy, ...
 ioPlotHistValues.h.G.Energy] = plotHist(nh1.G.Energy, ...
                                          h.G.Energy, ...
                                          ' stats G.Energy', ...
                                          iBinsValue);

subplot(2,2,4);
[ioPlotHistValues.nh1.G.Homogeneity, ...
 ioPlotHistValues.h.G.Homogeneity] = plotHist(nh1.G.Homogeneity, ...
                                          h.G.Homogeneity, ...
                                          ' stats G.Homogeneity', ...
                                          iBinsValue);

set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
saveas(gcf,'Result/graphHistorgamResults/G.jpg');
saveas(gcf,'Result/graphHistorgamResults/G.fig');

%-----------------Stats_B histogram------------------------------
figure;
set(gcf, 'Position', [300, 100, 800, 600]);
subplot(2,2,1);
[ioPlotHistValues.nh1.B.Contrast, ...
 ioPlotHistValues.h.B.Contrast] = plotHist(nh1.B.Contrast, ...
                                          h.B.Contrast, ...
                                          ' stats B.Contrast', ...
                                          iBinsValue);

subplot(2,2,2);
[ioPlotHistValues.nh1.B.Correlation, ...
 ioPlotHistValues.h.B.Correlation] = plotHist(nh1.B.Correlation, ...
                                             h.B.Correlation,...
                                             ' stats B.Correlation', ...
                                             iBinsValue);

subplot(2,2,3);
[ioPlotHistValues.nh1.B.Energy, ...
 ioPlotHistValues.h.B.Energy] = plotHist(nh1.B.Energy, ...
                                        h.B.Energy, ...
                                        ' stats B.Energy', ...
                                        iBinsValue);

subplot(2,2,4);
[ioPlotHistValues.nh1.B.Homogeneity, ...
 ioPlotHistValues.h.B.Homogeneity] = plotHist(nh1.B.Homogeneity, ...
                                             h.B.Homogeneity, ...
                                             ' stats B.Homogeneity', ...
                                             iBinsValue);

set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
saveas(gcf,'Result/graphHistorgamResults/B.jpg');
saveas(gcf,'Result/graphHistorgamResults/B.fig');

%-----------------Stats_RG histogram------------------------------
figure;
set(gcf, 'Position', [300, 100, 800, 600]);
subplot(2,2,1);
[ioPlotHistValues.nh1.RG.Contrast, ...
 ioPlotHistValues.h.RG.Contrast] = plotHist(nh1.RG.Contrast, ...
                                          h.RG.Contrast, ...
                                          ' stats RG.Contrast', ...
                                          iBinsValue);

subplot(2,2,2);
[ioPlotHistValues.nh1.RG.Correlation, ...
 ioPlotHistValues.h.RG.Correlation] = plotHist(nh1.RG.Correlation, ...
                                             h.RG.Correlation,...
                                             ' stats RG.Correlation', ...
                                             iBinsValue);

subplot(2,2,3);
[ioPlotHistValues.nh1.RG.Energy, ...
 ioPlotHistValues.h.RG.Energy] = plotHist(nh1.RG.Energy, ...
                                        h.RG.Energy, ...
                                        ' stats RG.Energy', ...
                                        iBinsValue);

subplot(2,2,4);
[ioPlotHistValues.nh1.RG.Homogeneity, ...
 ioPlotHistValues.h.RG.Homogeneity] = plotHist(nh1.RG.Homogeneity, ...
                                             h.RG.Homogeneity, ...
                                             ' stats RG.Homogeneity', ...
                                             iBinsValue);

set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
saveas(gcf,'Result/graphHistorgamResults/RG.jpg');
saveas(gcf,'Result/graphHistorgamResults/RG.fig');

%-----------------Stats_RB histogram------------------------------
figure;
set(gcf, 'Position', [300, 100, 800, 600]);
subplot(2,2,1);
[ioPlotHistValues.nh1.RB.Contrast, ...
 ioPlotHistValues.h.RB.Contrast] = plotHist(nh1.RB.Contrast, ...
                                          h.RB.Contrast, ...
                                          ' stats RB.Contrast', ...
                                          iBinsValue);

subplot(2,2,2);
[ioPlotHistValues.nh1.RB.Correlation, ...
 ioPlotHistValues.h.RB.Correlation] = plotHist(nh1.RB.Correlation, ...
                                             h.RB.Correlation,...
                                             ' stats RB.Correlation', ...
                                             iBinsValue);

subplot(2,2,3);
[ioPlotHistValues.nh1.RB.Energy, ...
 ioPlotHistValues.h.RB.Energy] = plotHist(nh1.RB.Energy, ...
                                        h.RB.Energy, ...
                                        ' stats RB.Energy', ...
                                        iBinsValue);

subplot(2,2,4);
[ioPlotHistValues.nh1.RB.Homogeneity, ...
 ioPlotHistValues.h.RB.Homogeneity] = plotHist(nh1.RB.Homogeneity, ...
                                             h.RB.Homogeneity, ...
                                             ' stats RB.Homogeneity', ...
                                             iBinsValue);

set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
saveas(gcf,'Result/graphHistorgamResults/RB.jpg');
saveas(gcf,'Result/graphHistorgamResults/RB.fig');

%-----------------Stats_GB histogram------------------------------
figure;
set(gcf, 'Position', [300, 100, 800, 600]);
subplot(2,2,1);
[ioPlotHistValues.nh1.GB.Contrast, ...
 ioPlotHistValues.h.GB.Contrast] = plotHist(nh1.GB.Contrast, ...
                                          h.GB.Contrast, ...
                                          ' stats GB.Contrast', ...
                                          iBinsValue);

subplot(2,2,2);
[ioPlotHistValues.nh1.GB.Correlation, ...
 ioPlotHistValues.h.GB.Correlation] = plotHist(nh1.GB.Correlation, ...
                                             h.GB.Correlation,...
                                             ' stats GB.Correlation', ...
                                             iBinsValue);

subplot(2,2,3);
[ioPlotHistValues.nh1.GB.Energy, ...
 ioPlotHistValues.h.GB.Energy] = plotHist(nh1.GB.Energy, ...
                                        h.GB.Energy, ...
                                        ' stats GB.Energy', ...
                                        iBinsValue);

subplot(2,2,4);
[ioPlotHistValues.nh1.GB.Homogeneity, ...
 ioPlotHistValues.h.GB.Homogeneity] = plotHist(nh1.GB.Homogeneity, ...
                                              h.GB.Homogeneity, ...
                                              ' stats GB.Homogeneity', ...
                                              iBinsValue);

set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
saveas(gcf,'Result/graphHistorgamResults/GB.jpg');
saveas(gcf,'Result/graphHistorgamResults/GB.fig');

end
