function [ioStatistics, ...
          ioTableColumns] = writeComponentResult(iResFileName, ...
                                                 iDiseaseCode, ...
                                                 iIndicator, ...
                                                 iComponentName, ...
                                                 iStats, ...
                                                 iMarks, ...
                                                 ioStatistics, ...
                                                 ioTableColumns)
%% WRITECOMPONENTRESULT 
% Summary of this function goes here. 
% 
% * Syntax 
% 
%	[OUTPUTARGS] = WRITECOMPONENTRESULT(INPUTARGS)
% 
% * Input 
% 
% -- INPUTARGS -  
% 
% * Output 
% 
% -- OUTPUTARGS -  
% 
% * Examples: 
% 
% Provide sample usage code here
% 
% * See also: 
% 
% List related files here 
% 
% * Author: Dmitrii Leliuhin 
% * Email: dleliuhin@mail.ru 
% * Date: 08/11/2018 10:18:07 
% * Version: 1.0 $ 
% * Requirements: PCWIN64, MatLab R2016a 
% 
% * Warning: 
% 
% # Warnings list. 
% 
% * TODO: 
% 
% # TODO list. 
% 

%% Code 

[ioStatistics, ...
 ioTableColumns] = writeComponentPropertyResult(iResFileName, ...
                                                iDiseaseCode, ...
                                                iIndicator, ...
                                                iComponentName, ...
                                                'Contrast', ...
                                                iStats, ...
                                                iMarks, ...
                                                ioStatistics, ...
                                                ioTableColumns);

[ioStatistics, ...
 ioTableColumns] = writeComponentPropertyResult(iResFileName, ...
                                                iDiseaseCode, ...
                                                iIndicator, ...
                                                iComponentName, ...
                                                'Correlation', ...
                                                iStats, ...
                                                iMarks, ...
                                                ioStatistics, ...
                                                ioTableColumns);
                                            
[ioStatistics, ...
 ioTableColumns] = writeComponentPropertyResult(iResFileName, ...
                                                iDiseaseCode, ...
                                                iIndicator, ...
                                                iComponentName, ...
                                                'Homogeneity', ...
                                                iStats, ...
                                                iMarks, ...
                                                ioStatistics, ...
                                                ioTableColumns);
                                            
[ioStatistics, ...
 ioTableColumns] = writeComponentPropertyResult(iResFileName, ...
                                                iDiseaseCode, ...
                                                iIndicator, ...
                                                iComponentName, ...
                                                'Energy', ...
                                                iStats, ...
                                                iMarks, ...
                                                ioStatistics, ...
                                                ioTableColumns);

end
