function writeXlsxGroupData(iTableFileName, ...
                            iLeaveGroup, ...
                            iStartColumn, ...
                            iStartRow)
%% WRITEXLSXGROUPDATA 
% Write current plantic iLeaveGroup statistic for each image from 
% this group to table in Result/Tables/iTableFileName.xlsx from 
% specifics iStartColumn and iStartRow.
% 
% * Syntax 
% 
%	[] = WRITEXLSXGROUPDATA(ITABLEFILENAME,   
%                           ILEAVEGROUP,
%                           ISTARTCOLUMN,
%                           ISTARTROW)
% 
% * Input 
% 
% -- iTableFileName - name of the file in which need to write averages.
% 
% -- iLeaveGroup - structure with healthy and diseased parts of a plants.
% 
% -- iStartColumn - column in table of iTableFileName from which need to 
%                   write data statistic.
%
% -- iStartRow - row in table of iTableFileName from which need to 
%                write data statistic.
% 
% * Examples: 
% 
% Provide sample usage code here
% 
% * See also: 
% 
% No relations.
% 
% * Author: Dmitrii Leliuhin 
% * Email: dleliuhin@mail.ru 
% * Date: 02/11/2018 01:00:23 
% * Version: 1.0 $ 
% * Requirements: PCWIN64, MatLab R2016a 
% 
% * Warning: 
% 
% # Warnings list. 
% 
% * TODO: 
% 
% # TODO list. 
% 

%% Code 

% Write statistic data for R component.
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.R.Contrast, ...
         strcat(iStartColumn, ...
                 num2str(iStartRow), ...
                  ':CD', ...
                   num2str(iStartRow)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.R.Correlation, ...
         strcat(iStartColumn, num2str(iStartRow + 1), ':CD', num2str(iStartRow + 1)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.R.Energy, ...
         strcat(iStartColumn, num2str(iStartRow + 2), ':CD', num2str(iStartRow + 2)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.R.Homogeneity, ...
         strcat(iStartColumn, num2str(iStartRow + 3), ':CD', num2str(iStartRow + 3)));

% Write statistic data for G component.
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.G.Contrast, ...
         strcat(iStartColumn, num2str(iStartRow + 4), ':CD', num2str(iStartRow + 4)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.G.Correlation, ...
         strcat(iStartColumn, num2str(iStartRow + 5), ':CD', num2str(iStartRow + 5)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.G.Energy, ...
         strcat(iStartColumn, num2str(iStartRow + 6), ':CD', num2str(iStartRow + 6)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.G.Homogeneity, ...
         strcat(iStartColumn, num2str(iStartRow + 7), ':CD', num2str(iStartRow + 7)));

% Write statistic data for B component.
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.B.Contrast, ...
         strcat(iStartColumn, num2str(iStartRow + 8), ':CD', num2str(iStartRow + 8)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.B.Correlation, ...
         strcat(iStartColumn, num2str(iStartRow + 9), ':CD', num2str(iStartRow + 9)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.B.Energy, ...
         strcat(iStartColumn, num2str(iStartRow + 10), ':CD', num2str(iStartRow + 10)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.B.Homogeneity, ...
         strcat(iStartColumn, num2str(iStartRow + 11), ':CD', num2str(iStartRow + 11)));

% Write statistic data for RG component.
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RG.Contrast, ...
         strcat(iStartColumn, num2str(iStartRow + 12), ':CD', num2str(iStartRow + 12)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RG.Correlation, ...
         strcat(iStartColumn, num2str(iStartRow + 13), ':CD', num2str(iStartRow + 13)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RG.Energy, ...
         strcat(iStartColumn, num2str(iStartRow + 14), ':CD', num2str(iStartRow + 14)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RG.Homogeneity, ...
         strcat(iStartColumn, num2str(iStartRow + 15), ':CD', num2str(iStartRow + 15)));

% Write statistic data for RB component.
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RB.Contrast, ...
         strcat(iStartColumn, num2str(iStartRow + 16), ':CD', num2str(iStartRow + 16)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RB.Correlation, ...
         strcat(iStartColumn, num2str(iStartRow + 17), ':CD', num2str(iStartRow + 17)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RB.Energy, ...
         strcat(iStartColumn, num2str(iStartRow + 18), ':CD', num2str(iStartRow + 18)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.RB.Homogeneity, ...
         strcat(iStartColumn, num2str(iStartRow + 19), ':CD', num2str(iStartRow + 19)));

% Write statistic data for GB component.
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.GB.Contrast, ...
         strcat(iStartColumn, num2str(iStartRow + 20), ':CD', num2str(iStartRow + 20)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.GB.Correlation, ...
         strcat(iStartColumn, num2str(iStartRow + 21), ':CD', num2str(iStartRow + 21)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.GB.Energy, ...
         strcat(iStartColumn, num2str(iStartRow + 22), ':CD', num2str(iStartRow + 22)));
xlswrite(strcat('Result/Tables/', iTableFileName, '.xlsx'), ...
         iLeaveGroup.GB.Homogeneity, ...
         strcat(iStartColumn, num2str(iStartRow + 23), ':CD', num2str(iStartRow + 23)));

end
